# ----------------------------------------------------------------------------------------------------------------------
#  Weave
#  Created by SpektrSoyuz
#
#  GitHub:  https://github.com/spektrsoyuz/weave
#  Discord: https://discord.gg/PLACEHOLDER
#  Website: https://spektrsoyuz.com
#
# ----------------------------------------------------------------------------------------------------------------------
database:
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  table_prefix: weave

redis:
  host: localhost
  port: 6379
  password: password